C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.01 1
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.01 2
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.01 3
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.01 4
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.01 5
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.01 6
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.01 7
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.015 1
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.015 2
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.015 3
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.015 4
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.015 5
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.015 6
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.015 7
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.02 1
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.02 2
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.02 3
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.02 4
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.02 5
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.02 6
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.02 7
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.005 1
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.005 2
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.005 3
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.005 4
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.005 5
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.005 6
C:/Users/sch401/AppData/Local/Programs/Python/Python310/python.exe "D:/Doctor_Thesis/database and website/code/3_Different ML model training and selection with selected feature/ANNoptimize/ANN2findlearningrate nodenumber.py" 0.005 7


pause
